### ISSUE TITLE
Editing string lookup files

### ISSUE THREAD

**Issue by tytannial** [Ryder25/Rise-of-Legends#1]
The extracted XML from strings.big and nonloc_strings.big with a strange suffix "lookups" and can't read by text editor.

**Comment by Ryder25** [comment]
While they may have an xml extension they are actually a different file type.  Another program would have to be made to convert them to regular human readable xml format.

**Comment by tytannial** [comment]
:disappointed_relieved: Did you have time for it? It seems like the only way modify localization.

**Comment by Ryder25** [comment]
Sorry, I will not be making a program for this.

**Comment by tytannial** [comment]
hum...I will have a try analysing those files. Thank you for making this nice tool. :D
